### ISSUE TITLE
首页进入文档超链接不能自定义文字

### ISSUE THREAD

**Issue by JaveHub** [dumindu/E25DX#1]
![image](https://github.com/user-attachments/assets/26fce9aa-b61f-41a2-87d6-329f08f1d46a)

**Comment by dumindu** [comment]
Lang: https://github.com/dumindu/E25DX/blob/main/i18n/en.yaml#L2
Link: https://github.com/dumindu/E25DX/blob/main/hugo.yaml#L50

**Comment by dumindu** [comment]
Need to search and replace; `//localhost:1313` -> `https://javehub.github.io` and remove 
`<script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>` inside files in the public folder. Give me today and tomorrow, I'll try to automate deploy site via GitHub actions with correct host URL.

**Comment by dumindu** [comment]
@JaveHub https://github.com/JaveHub/JaveHub.github.io/pull/1

**Comment by dumindu** [comment]
> Need to search and replace; `//localhost:1313` -> `https://javehub.github.io` and remove `<script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>` inside files in the public folder. Give me today and tomorrow, I'll try to automate deploy site via GitHub actions with correct host URL.

@JaveHub For deployments refer, https://gohugo.io/commands/hugo_build/
This might be the command `hugo build --enableGitInfo --disableLiveReload --baseURL https://javehub.github.io/`
