### ISSUE TITLE
部署到github后点击get start跳转到了localhost:3131地址

### ISSUE THREAD

**Issue by JaveHub** [dumindu/E25DX#2]
![image](https://github.com/user-attachments/assets/71f8a652-fda3-4d0b-af7e-d19972a73bbd)
![image](https://github.com/user-attachments/assets/1558d8e2-3aa1-4db7-9624-d66bea1a9c2e)
![image](https://github.com/user-attachments/assets/7af31ee7-b401-41d6-8584-b9fc738d49c9)

**Comment by dumindu** [comment]
@JaveHub https://github.com/JaveHub/JaveHub.github.io/pull/1

**Comment by dumindu** [comment]
https://github.com/dumindu/E25DX/issues/1#issuecomment-2537757012

**Comment by dumindu** [comment]
https://github.com/dumindu/E25DX/issues/1#issuecomment-2539702210

> @JaveHub For deployments refer, https://gohugo.io/commands/hugo_build/
> This might be the command `hugo build --enableGitInfo --disableLiveReload --baseURL https://javehub.github.io/`
